import React from 'react';

export default function Footer() {
  return (
    <footer className="nav-footer">
      <div className="padding-global"><div className="container-xlarge"><div className="section-wrapper"><div id="w-node-cdf875e1-dbb6-ae31-f653-66ab70fecf28-70fecf24" className="section-title-panel"><div className="section-text-label accent-color-2b"><div>Navigation</div></div><div className="section-panel-border opacity-white-50"></div></div><div id="w-node-cdf875e1-dbb6-ae31-f653-66ab70fecf2c-70fecf24" className="nav-footer-content"><div className="padding-vertical padding-huge"><div className="content-main"><div className="grid-2-1-column _1-column-tablet"><div id="w-node-cdf875e1-dbb6-ae31-f653-66ab70fecf3f-70fecf24" className="flex-box-vertical flex-space-between"><div className="nav-footer-menu"><div id="w-node-cdf875e1-dbb6-ae31-f653-66ab70fecf40-70fecf24" className="nav-menu-list"><a href="/" aria-current="page" className="nav-footer-link w--current">Home</a><a href="/about" className="nav-footer-link">About</a><a href="/case-studies" className="nav-footer-link">Projects</a><a href="/faqs" className="nav-footer-link">Services</a><a href="/contact" className="nav-footer-link">Contact</a></div><div id="w-node-cdf875e1-dbb6-ae31-f653-66ab70fecf4b-70fecf24" className="nav-menu-list"></div><div id="w-node-cdf875e1-dbb6-ae31-f653-66ab70fecf60-70fecf24" className="nav-menu-list"><a href="/privacy-policy" className="nav-footer-link">Privacy Policy</a><a href="/terms-and-conditions" className="nav-footer-link">Terms &amp; Conditions</a><a href="/cookies" className="nav-footer-link">Cookie Policy</a></div></div><p className="text-size-small">© 2026 TMP Architecture Ltd. All rights reserved. Website designed by <a href="https://cornerstonedg.com/" target="_blank" rel="noopener noreferrer" style={{color:'var(--color-gold)'}}>Cornerstone Digital</a></p></div><div id="w-node-cdf875e1-dbb6-ae31-f653-66ab70fecf67-70fecf24" className="form-block newsletter-signup w-form"><form id="email-form" name="email-form" data-name="Email Form" method="get" className="form" data-wf-page-id="68716f8967be25f86faf6eee" data-wf-element-id="cdf875e1-dbb6-ae31-f653-66ab70fecf68"><h3>Stay inspired. Build better.</h3><p className="text-size-medium">Get tips on extensions, planning permission and making the most of your property</p><div className="form-field-wrapper"><label htmlFor="Email-3" className="field-label">Email Address</label><input className="text-field inverted w-input" maxLength="256" name="Email" data-name="Email" placeholder="Email address" type="email" id="Email-3" required=""/><p className="text-size-small">No spam, unsubscribe at any time</p></div><input type="submit" data-wait="Please wait..." className="button-form w-button" value="Sign-up"/></form><div className="success-message w-form-done"><div>Thank you! Your submission has been received!</div></div><div className="error-message w-form-fail"><div>Something went wrong while submitting the form. Please try again.</div></div></div></div></div></div></div></div></div></div>
    </footer>
  );
}
