import React from 'react';
import { Link, NavLink } from 'react-router-dom';

export default function Navbar() {
  return (
    <nav className="nav-bar">
      <div className="padding-global"><div className="nav-container"><a aria-label="Brand home page link" href="/" aria-current="page" className="brand-link w-inline-block w--current"><svg width="90" height="24" viewBox="0 0 90 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="TMP Architecture"><g fill="#292a2a"><polygon points="12,2 22,13 2,13" strokeLinejoin="round"/><rect x="8" y="13" width="8" height="9"/></g><text x="28" y="17" fontFamily="'Satoshi', sans-serif" fontWeight="700" fontSize="14" letterSpacing="0.12em" fill="#292a2a">TMP</text></svg></a><div data-w-id="8572d262-4219-604f-ecba-d4bf5c31cb2f" className="nav-menu"><div className="nav-icon"></div><div className="text-container"><div className="text-block">Menu</div><div className="text-block">Menu</div></div></div><div className="nav-menu-overlay"><div className="padding-global"><div className="container-xlarge"><div className="section-wrapper"><div className="section-title-panel"><div className="section-panel-border"></div><div className="section-text-label"><div>Navigation</div></div></div><div id="w-node-_8572d262-4219-604f-ecba-d4bf5c31cb3a-5c31cb2a" className="nav-menu-content"><a href="/" aria-current="page" className="nav-link-container w-inline-block w--current"><div className="icon-medium"><div className="text-size-large">1</div></div><div className="nav-menu-link">Home</div></a><a href="/about" className="nav-link-container w-inline-block"><div className="icon-medium"><div className="text-size-large">2</div></div><div className="nav-menu-link">About</div></a><a href="/projects" className="nav-link-container w-inline-block"><div className="icon-medium"><div className="text-size-large">3</div></div><div className="nav-menu-link">Projects</div></a><a href="/services" className="nav-link-container w-inline-block"><div className="icon-medium"><div className="text-size-large">4</div></div><div className="nav-menu-link">Services</div></a><a href="/contact" className="nav-link-container w-inline-block"><div className="icon-medium"><div className="text-size-large">5</div></div><div className="nav-menu-link">Contact</div></a></div></div></div></div></div></div></div>
    </nav>
  );
}
